### PR TITLE
Initial implementation on building

### PR DESCRIPTION
**Pull request by andylokandy**
Commit overview:

- Refactor `err.rs`: use native `Error` of `failure` intead of the homemade one so as to get more flexibility. This is a blocking issue of implementing `ProcessBuilder`.

- Add `CompileInvocation` and `CodegenInvocation` which actually invokes idris compiler, in single thread.
  
- Add `BuildContext` which intends to store the resolve graph and cache, `TargetDir` which defines the layout of build directory and `Compiler` which is responsible to lookup idris compiler.

The names and file structure might need to be discussed.

### CODE REVIEW

**Comment by andylokandy** [comment]
The build directory structure learns from cargo; the current implementation is roughly:

```
/build
  Lib.idr
  Dep1.ibc
  Dep2.ibc
/deps
  Dep1.ibc
  Dep2.ibc
Lib.ibc
```

where `/build` would be removed after compilation.

**Comment by dcao** [comment]
Overall, these changes look really good! I just have some concerns about the design of `TargetDir`. I was originally planning on following the design of cabal's [nix-style local builds](https://www.haskell.org/cabal/users-guide/nix-local-build-overview.html), in which builds are globally cached so that different projects don't rebuild the same dependencies over and over. Under this design, the `Cache` would be in charge of caching the tree of ibc files for each of the dependencies, with the `TargetDir` only handling builds for the current root package, generating docs, etc.

Even if we were to follow a cargo-esque route for the target directory, each built dependent package would have multiple ibc files, not just one, so we'd have to have a directory for the ibc files of each package.

**Comment by andylokandy** [comment]
`TargetDir` is designed with global caching in mind; we could just point the target dir to a global directory provided by cache. Thus, we actually need a directory for each library.

**Comment by andylokandy** [comment]
Blocking on dependency resolving.

**Comment by dcao** [comment]
Dependency resolution now returns a `Graph<Summary, ()>`, so you should be able to add that into the `BuildContext` now.

**Comment by andylokandy** [comment]
There are many changes today, so I'm gonna summary it up:

- add `Resolve`, a wrapper of resolve graph, providing useful functionalities (only looking for deps right now).

- add `Build`, representing a build version of library which varies for different dependency tree; add `Source`, which points to the directory of source code retrieved into local; add `Binary`, pointing to the cached build.

- add `JobQueue` and `Job`, which are used to setup a build plan.

**Comment by andylokandy** [comment]
I think it's time to merge this PR now (๑•̀ㅂ•́)و✧; I'll start further work in the other thread.

**Comment by andylokandy** [comment]
I have an initial idea about build directory layout: for root package, we build under /target/build and then copy the output into /target; for dependencies, we build in a tmp directory like ~/.elba/build/lightyear-0.1.0-hash/build, after compilation, we store it as ~/.elba/libraries/lightyear-0.1.0-hash.ibc. Finally, we remove the tmp build directory after each successful compilation of the library.

**Comment by dcao** [comment]
My idea for the build process would be you start with the packages with no dependencies, throw the ibc output files of those packages into their respective folders (`~/.elba/build/*`), then for each package up the chain, just add the directory of the built packages it depends on as an additional import path. In this way, we can globally cache built packages and keep the structure simple.

Additionally, I don't think you can build a package into a single idr file (although I'm not too familiar with the incantations required to work the Idris compiler; you know more here than I do)

**Comment by andylokandy** [comment]
Since arbitrary name of library source is allowed, we might have to keep track of the name of binary in the build folder. For example, if the library `Lightyear` exports its interface by `/src/LibABC.idr`, the build of it will be `/build/LibABC.ibc`, which have to be keep tracked somewhere so that dependents are be able to check it out later. If we cache the binary as a single file, it will be dead simple to find cache by only checking if the file exists.

> Additionally, I don't think you can build a package into a single idr file

Idris compiler has been generating a package into a single ibc file, when the other generated ibc is discardable.

> I guess I don't really understand why we would need separate build/ and libraries/ directories, as well as why we would need a build/ subfolder for every package.

I explained why we should have a libraries/ folder above; the build/ folder is useless after compilation, yet it's useful to debug and profile the building process when compilation fails.

**Comment by andylokandy** [comment]
I noticed that you add a factor, the location from which the source code was retrieved, to compute the hash of build.

That is great! The source from direct resolution is not trusted. Unless we host the source on index, we should always verify it.

However, it's not sufficient to ensure that it is the source we want. For example, the head of a git branch can change overtime; the files on local resolution can also change without breaking the resolution, therefore, I think it's better to check the hash of source **files**, instead of the location from which they come from.

**Comment by dcao** [comment]
- **Folder structure**: in that case, why don't we unify the `libraries/` and `build/` directories? During building, the files get put into `~/.elba/build/whatever/build/`, then afterwards the single ibc is put under `~/.elba/build/whatever/whatever.ibc`. Would that work?
- **Build hashes**: that's a good point; we'll have to figure out how we can do hashing of a complete directory tree, though, and whether that'll be performant (using [walkdir](https://github.com/BurntSushi/walkdir) perhaps?). I don't think we lose anything by storing Summaries instead of Sources in the graph though, since we can always get the corresponding Source of a Summary by just asking the Cache for this info.

**Comment by andylokandy** [comment]
- **Folder structure**:

> During building, the files get put into ~/.elba/build/whatever/build/, then afterwards the single ibc is put under ~/.elba/build/whatever/whatever.ibc. Would that work?

Yes, we could put the single ibc under build folder (like /.elba/build/libname-0.1.0-hash/libname-0.1.0-hash.ibc, so that we can compute the path to it without doing IO). But I prefer storing the ibcs in a more concise way, without any intermediately generated stuffs.(The build/ folder should be empty after compilation)

- **Hashes**

> I don't think we lose anything by storing Summaries instead of Sources in the graph though, since we can always get the corresponding Source of a Summary by just asking the Cache for this info.

I agree. I'm also doing research on what the information is needed for each part in each stages, and I realized that the hash of source code is only required by build hashing. The reason why I decided to store it in `Solve` is that a full denpendency graph of source hash is needed to compute a build hash(I may explain it later if it is not clear), so although it is not necessary to have the `Solve` to carry information of source hash, we acutally need a graph like `Graph<(Summary, HashOfSource)>`, which is viable by requiring `Cache` to construct the graph from `Solve`.

**Comment by andylokandy** [comment]
If we're going to have to two versions of graph, it will be a small problem that we have to duplicate the graph wrapper to provide `.deps()`.

**Comment by dcao** [comment]
One solution to code duplication is that you could just make `Solve` generic over the Graph node type. Nothing in the `Solve` struct at the moment is inherently Summary-specific, so I think that would work.

With regards to when to resolve dependencies and download packages, we have to resolve the specific versions of the dependencies before we can download them; if my root package depends on `andylokandy/parser ≥ 1.0.0`, I have to figure out which version of your package I want before I can download it.

Two packages with the same name but different resolutions will be viewed as just that: different packages.  The biggest problem I could see happening is that namespaces will end up colliding, and packages with different resolutions but the same name will both try using the same namespace, leading to who knows what. Cargo's solution to this problem is requiring that all of the crate names used in a package are unique, and enforcing this by letting the user rename crates in their manifest so that in the source code, the crates' names don't collide, which I think is a good solution.

**Comment by andylokandy** [comment]
Overally agree. And we should put aside the name collision and list it in known issues, right?

**Comment by dcao** [comment]
After some mulling over and experimentation, I think I've found a way to avoid name collisions completely. I've opened #3 for further discussion on this new build approach.

**Pull request merged**
